### PR TITLE
fix(task): fixing clone_config variables

### LINKED ISSUE #156: Bug: Task::shell cannot choose which config file / ansible-bash is used
**Describe the bug**
running `vlab shell` only connects to prod

### PR DESCRIPTION
**Pull request by denis-ev**
closes #156

### CODE REVIEW

File: tasks/LifecyleTasks.sh [hunk 1]
```diff
@@ -59,7 +58,7 @@ Task::stop(){
 
   highlight "Stopping all services"
   Task::run_docker ansible-playbook $(debug_check) $(sshkey_path) \
-  --extra-vars="@$_config_dir/$_user_config-config.yml" --extra-vars="@$_config_dir/$_user_config-vault.yml" \
+  --extra-vars="@$_config_dir/$_user_config-config.yml" --extra-vars="@$_config_dir/$_user_config-" \
```
Comment (denis-ev) [inline tasks/LifecyleTasks.sh:61]:
```suggestion
  --extra-vars="@$_config_dir/$_user_config-config.yml" --extra-vars="@$_config_dir/$_user_config-vault.yml" \
```
fixing typo

**Review by voryzen — APPROVED** [review]
Just merge.

We will deal with the issues, later

**Comment by denis-ev** [comment]
> Just merge.
> 
> We will deal with the issues, later

What issues? I would like to fix them right away.
